package csg;

/**
 * This enum provides a list of all the user interface
 * text that needs to be loaded from the XML properties
 * file. By simply changing the XML file we could initialize
 * this application such that all UI controls are provided
 * in another language.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum TAManagerProp {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    UNDER_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    START_COMBO_TEXT,
    END_COMBO_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    ADD_BUTTON_TEXT_1,
    CHANGE_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT_1,
    EDIT_BUTTON_TEXT,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    INVALID_EMAIL_TITLE,
    INVALID_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    
    COMBO_BOX_TIME_ERROR_TITLE,
    COMBO_BOX_TIME_ERROR_MESSAGE,
    COMBO_BOX_CUT_TA_TITLE,
    COMBO_BOX_CUT_TA_MESSAGE,
    
    // PROMT
    COURSE_TITLE_PROMT,
    COURSE_INSTRUCTOR_NAME_PROMT,
    COURSE_INSTRUCTOR_HOME_PROMT,
    
    // Button
    ADD_ICON,
    CLEAR_ICON,
    EDIT_ICON,
    REMOVE_ICON,
    CHANGE_ICON,
    YALE_UNIVERSITY_ICON,
    YALE_CS_ICON,
    
    // Tooltip
    ADD_TOOLTIP,
    CLEAR_TOOLTIP,
    EDIT_TOOLTIP,
    REMOVE_TOOLTIP,
    CHANGE_TOOLTIP,
    
    // pane
    COURSE,
    TADATA,
    RECITATION,
    SCHEDULE,
    PROJECT,
    
    // Course Deatail properties
    COURSE_SELETCT_TEMPLATE_BUTTON,
    COURSE_INFO_HEADER,
    COURSE_INFO_SUBJECT,
    COURSE_INFO_NUMBER,
    COURSE_INFO_SEMESTER,
    COURSE_INFO_YEAR,
    COURSE_INFO_TITLE,
    COURSE_INFO_INSTRUCTOR,
    COURSE_INFO_HOME,
    COURSE_INFO_EXPORT,
    
    SITE_TEMPLATE_HEADER,
    SITE_TEMPLATE_EXPLATION,
    SITE_TEMPLATE_SITE_PAGE,
    SITE_TEMPLATE_USE,
    SITE_TEMPLATE_NAVBAR_TITLE,
    SITE_TEMPLATE_FILE_NAME,
    SITE_TEMPLATE_SCRIPT,
    
    PAGE_STYLE_HEADER,
    PAGE_STYLE_BANNER,
    PAGE_STYLE_LEFT_FOOTER,
    PAGE_STYLE_RIGHT_FOOTER,
    PAGE_STYLE_STYLESHEET,
    PAGE_STYLE_NOTE,
    
    RECITATION_HEADER,
    RECITATION_SECTION_COLUMN,
    RECITATION_INSTRUCTOR_COLUMN,
    RECITATION_DAY_COLUMN,
    RECITATION_LOCATION_COLUMN,
    RECITATION_TA1_COLUMN,
    RECITATION_TA2_COLUMN,
    RECITATION_ADD_HEADER,
    RECITATION_SECTION,
    RECITATION_INSTRUCTOR,
    RECITATION_DAY,
    RECITATION_LOCATION,
    RECITATION_TA1,
    RECITATION_TA2,
    
    SCHEDULE_HEADER,
    SCHEDULE_CALENDAR,
    SCHEDULE_START_MON,
    SCHEDULE_START_FRI,
    SCHEDULE_ITEMS,
    SCHEDULE_TYPE_COL,
    SCHEDULE_DATE_COL,
    SCHEDULE_TITLE_COL,
    SCHEDULE_TOPIC_COL,
    SCHEDULE_ADD_HEADER,
    SCHEDULE_TYPE,
    SCHEDULE_DATE,
    SCHEDULE_TIME,
    SCHEDULE_TITLE,
    SCHEDULE_TOPIC,
    SCHEDULE_LINK,
    SCHEDULE_CRITERIA,
    
    PROJECT_HEADER,
    PROJECT_TEAMS_HEADER,
    PROJECT_TEAMS_NAME_COL,
    PROJECT_TEAMS_COLOR_COL,
    PROJECT_TEAMS_TEXTCOLOR_COL,
    PROJECT_TEAMS_LINK_COL,
    PROJECT_TEAMS_ADD_HEADER,
    PROJECT_TEAMS_NAME,
    PROJECT_TEAMS_COLOR,
    PROJECT_TEAMS_LINK,
    PROJECT_STUDENTS_HEADER,
    PROJECT_STUDENTS_FIRSTNAME_COL,
    PROJECT_STUDENTS_LASTNAME_COL,
    PROJECT_STUDENTS_TEAM_COL,
    PROJECT_STUDENTS_ROLE_COL,
    PROJECT_STUDENTS_ADD_HEADER,
    PROJECT_STUDENTS_FIRSTNAME,
    PROJECT_STUDENTS_LASTNAME,
    PROJECT_STUDENTS_TEAM,
    PROJECT_STUDENTS_ROLE,
    
    
    
}
